### PR TITLE
Add support for GitHub Actions

### PR DESCRIPTION
**Pull request by tavip**
Add initial support for building the documentation via GitHub
Actions. Does not yet include support for automatically publishing to
GitHub Pages.

Signed-off-by: Octavian Purdila <tavi@cs.pub.ro>

### CODE REVIEW

**Comment by dbaluta** [comment]
@tavip out of curiosity is Github actions better than Travis? Why do we need to change this?

**Comment by tavip** [comment]
@dbaluta we are not using Travis, we are using CircleCI. Using GitHub actions is a bit easier since the CI management is part of GitHub, we don't need separate accounts, etc. At this point I just want to experiment.

**Comment by dbaluta** [comment]
@tavip I see. thanks.

**Comment by razvand** [comment]
I think this is OK, even more so for experimenting. Let's see how it goes.

**Pull request closed without merging**
