### PR TITLE
Add kernel API assignment 

### PR DESCRIPTION
**Pull request by dbaluta**

### CODE REVIEW

**Comment by alexandrasandulescu** [comment]
@dbaluta, the module must be moved to checker directory or the other way around. I suggest passing module path as parameter to checker script. Also, grant executable permissions to user for checker script.

**Comment by dbaluta** [comment]
@alexandrasandulescu the checker script is already executable. For the module path parameter I assumed that vmchecker will make sure that the module is copied in the checker directory. I will fix that after I will understand how vmchecker does the testing.

**Comment by alexandrasandulescu** [comment]
@dbaluta , I was thinking about moving the kernel module inside vm directories while testing locally.

**Comment by dbaluta** [comment]
@alexandrasandulescu I get your point. I will have a look at this later. Can you approve the PR now. Wills end a separate patch.

**Pull request merged**
