### PR TITLE
Refactor assignments

### PR DESCRIPTION
**Pull request by razvand**
I've made an update to the file system structure for assignments templates. This is currently used in vmchecker. @alexandrasandulescu , please take a look. Is this OK with you?

We can remove the numbering prefix (i.e. use `tracer` instead of `1-tracer`); this will require an updated to the `config` file in vmchecker.

### CODE REVIEW

**Comment by dbaluta** [comment]
I am OK with the changes. @razvand for the next patches please use tags for commit message.

Like for example: Documentation: labs: ...

**Comment by razvand** [comment]
@alexandrasandulescu , do you think we should remove the numbering prefix and leave only the assignment name as it was in the old repository (i.e. use `tracer` instead of `1-tracer` and `list` instead of `0-list`)?

**Comment by razvand** [comment]
@dbaluta, so it should be as below?
```
Documentation:tools:labs: Use assignments subfolder for assignments
```

Is there a guideline for this?

**Comment by razvand** [comment]
@alexandrasandulescu, OK, we'll keep prefixes for the time being. Please to the same for the next assignments.

**Comment by dbaluta** [comment]
@razvand adding tags to commit message is a common practice in the Linux kernel. If not sure what tag to use just see git log around the directory / file you changed and use the tags from previous commits.

**Comment by razvand** [comment]
@dbaluta, I've added the `Documentation: tools :labs` prefix to all commits. I will merge this PR after you approve it.

**Pull request merged**
