### PR TITLE
Documentation: teaching: Fix typos about pr_debug

### PR DESCRIPTION
**Pull request by ciocancosmin98**
Fix typos about pr_debug and pr_warn.

### CODE REVIEW

**Review by dbaluta — APPROVED** [review]

**Comment by dbaluta** [comment]
@ciocancosmin98 looks good. Few comments about commit message.

Check this: https://chris.beams.io/posts/git-commit/#seven-rules

We should imperative mood for commit message and trim the prefix as much as possible:

`Documentation: teaching: Fix some typos about pr_debug `

**Review by tavip — APPROVED** [review]

**Comment by dbaluta** [comment]
@ciocancosmin98 you don;t have to change the Title of the PR but the title of the commit message. 

In your repo just run `git commit --amend` do the modifications and then force push the patch onto your github repo. Then it will be automatically updated here.

**Review by valighita — APPROVED** [review]

**Comment by ciocancosmin98** [comment]
@dbaluta Sorry it took awhile for me to do this. I hope it's okay now.

**Comment by dbaluta** [comment]
@ciocancosmin98 hmm, you now have 3 commits this is not OK. You should only have the initial commit but with the changes amended

Use `git rebase -i HEAD~3` and get rid of the 'Merge commit' then also squash the previous commits into a single one. 

Or you can just start over:
1) Save your work into a separate branch
2) Go back to the initial branch and synchronize your work with the remote branch
* git fetch origin
* git rebase --hard origin/master
3) Apply your patch or recreate it.

**Comment by dbaluta** [comment]
@ciocancosmin98 Let me know when you have some time I can just show you how to fix this on teams.

**Comment by ciocancosmin98** [comment]
I just remade the pull request, if that's okay.

**Comment by dbaluta** [comment]
Yes, that's the easy way out when you are just starting with github PRs and git :)

**Pull request closed without merging**
