### PR TITLE
Adding bison and flex as requirements for virtual machine setup.

### PR DESCRIPTION
**Pull request by gabrielmocanu**

### CODE REVIEW

**Comment by doringeman** [comment]
This is already being done in https://github.com/linux-kernel-labs/linux/pull/244.
https://github.com/linux-kernel-labs/linux/pull/244/commits/83be96bc44324b9b1a1c7584707e77bde5c47537#diff-df3fd5fe4f330b18c3d97c0b3a46094d51fc85c8bfb6bac1ea6c17ea3e9e6fd9R14

**Comment by gabrielmocanu** [comment]
@razvand  was faster than me with #244.
I think this PR can be closed.

**Comment by doringeman** [comment]
You can add those in the Dockerfile as requested [here](https://github.com/linux-kernel-labs/linux/pull/244#discussion_r588459953).

**Comment by razvand** [comment]
@gabrielmocanu , for future reference please add a tag to the commit message, i.e. `Documentation: teaching:`. See [here](https://linux-kernel-labs.github.io/refs/heads/master/info/contributing.html#creating-a-pull-request) (item 4).

**Pull request closed without merging**
